export const MockData = [
  {
    id: 1,
    job_title: 'Marketing Assistant',
    job_category: 'Other Specialty Stores',
    posted: '7/21/2022',
    no_of_position: 1,
  },
  {
    id: 2,
    job_title: 'Actuary',
    job_category: 'n/a',
    posted: '11/19/2021',
    no_of_position: 2,
  },
  {
    id: 3,
    job_title: 'Desktop Support Technician',
    job_category: 'Business Services',
    posted: '1/9/2022',
    no_of_position: 3,
  },
  {
    id: 4,
    job_title: 'Systems Administrator II',
    job_category: 'Medical/Dental Instruments',
    posted: '2/8/2022',
    no_of_position: 4,
  },
  {
    id: 5,
    job_title: 'Senior Developer',
    job_category: 'Medical/Dental Instruments',
    posted: '10/14/2021',
    no_of_position: 5,
  },
  {
    id: 6,
    job_title: 'Physical Therapy Assistant',
    job_category: 'Computer Software: Prepackaged Software',
    posted: '4/22/2022',
    no_of_position: 6,
  },
  {
    id: 7,
    job_title: 'Chief Design Engineer',
    job_category: 'Medical/Dental Instruments',
    posted: '2/13/2022',
    no_of_position: 7,
  },
  {
    id: 8,
    job_title: 'Senior Financial Analyst',
    job_category: 'n/a',
    posted: '8/14/2021',
    no_of_position: 8,
  },
  {
    id: 9,
    job_title: 'Media Manager II',
    job_category: 'Clothing/Shoe/Accessory Stores',
    posted: '4/6/2022',
    no_of_position: 9,
  },
]
